/****************************************************************************
 * boards/arm/stm32/stm32f407zg-pfcllc/include/board.h
 *
 * SPDX-License-Identifier: Apache-2.0
 ****************************************************************************/

#ifndef __BOARDS_ARM_STM32_STM32F407ZG_PFCLLC_INCLUDE_BOARD_H
#define __BOARDS_ARM_STM32_STM32F407ZG_PFCLLC_INCLUDE_BOARD_H

#include <nuttx/config.h>

/* 8 MHz HSE -> 168 MHz SYSCLK.  APB1 is 42 MHz and APB2 is 84 MHz. */

#define STM32_BOARD_XTAL        8000000ul
#define STM32_HSI_FREQUENCY     16000000ul
#define STM32_LSI_FREQUENCY     32000
#define STM32_HSE_FREQUENCY     STM32_BOARD_XTAL
#define STM32_LSE_FREQUENCY     32768

#define STM32_PLLCFG_PLLM       RCC_PLLCFG_PLLM(8)
#define STM32_PLLCFG_PLLN       RCC_PLLCFG_PLLN(336)
#define STM32_PLLCFG_PLLP       RCC_PLLCFG_PLLP_2
#define STM32_PLLCFG_PLLQ       RCC_PLLCFG_PLLQ(7)

#define STM32_SYSCLK_FREQUENCY  168000000ul
#define STM32_RCC_CFGR_HPRE     RCC_CFGR_HPRE_SYSCLK
#define STM32_HCLK_FREQUENCY    STM32_SYSCLK_FREQUENCY
#define STM32_RCC_CFGR_PPRE1    RCC_CFGR_PPRE1_HCLKd4
#define STM32_PCLK1_FREQUENCY   (STM32_HCLK_FREQUENCY / 4)
#define STM32_RCC_CFGR_PPRE2    RCC_CFGR_PPRE2_HCLKd2
#define STM32_PCLK2_FREQUENCY   (STM32_HCLK_FREQUENCY / 2)

#define STM32_APB1_TIM2_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM3_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM4_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM5_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM6_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM7_CLKIN   (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM12_CLKIN  (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM13_CLKIN  (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB1_TIM14_CLKIN  (2 * STM32_PCLK1_FREQUENCY)
#define STM32_APB2_TIM1_CLKIN   (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM8_CLKIN   (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM9_CLKIN   (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM10_CLKIN  (2 * STM32_PCLK2_FREQUENCY)
#define STM32_APB2_TIM11_CLKIN  (2 * STM32_PCLK2_FREQUENCY)

#define BOARD_TIM1_FREQUENCY    STM32_HCLK_FREQUENCY
#define BOARD_TIM2_FREQUENCY    (STM32_HCLK_FREQUENCY / 2)
#define BOARD_TIM3_FREQUENCY    (STM32_HCLK_FREQUENCY / 2)
#define BOARD_TIM4_FREQUENCY    (STM32_HCLK_FREQUENCY / 2)
#define BOARD_TIM5_FREQUENCY    (STM32_HCLK_FREQUENCY / 2)
#define BOARD_TIM6_FREQUENCY    (STM32_HCLK_FREQUENCY / 2)
#define BOARD_TIM7_FREQUENCY    (STM32_HCLK_FREQUENCY / 2)
#define BOARD_TIM8_FREQUENCY    STM32_HCLK_FREQUENCY

/* Dedicated interfaces:
 *
 * USART1 PA9/PA10: NSH console and boot diagnostics.
 * USART6 PC6/PC7 : Qt binary protocol only.
 * CAN1   PA11/12 : PFC/LLC bus, configured for 125 kbit/s in defconfig.
 */

#define GPIO_USART1_TX          GPIO_USART1_TX_1
#define GPIO_USART1_RX          GPIO_USART1_RX_1
#define GPIO_USART6_TX          GPIO_USART6_TX_1
#define GPIO_USART6_RX          GPIO_USART6_RX_1
#define GPIO_CAN1_RX            GPIO_CAN1_RX_3
#define GPIO_CAN1_TX            GPIO_CAN1_TX_3

#endif
